title: "Data Exchange Kennisbank"
description: "Kennisbank voor ICT-professionals in financiële Data Exchange"
baseurl: "/dexc-kennisbank"
url: "https://dma61.github.io"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
